import type { Env } from '../types/env';
import type { Track } from '../types/music';
import { RecommendationService, WAVE_MOODS, type WaveMood } from './RecommendationService';
import { TasteService } from './TasteService';
import { TidalService } from './tidal/TidalService';
import { loadDislikes, filterTracksByDislikes } from './dislikes';
import { getCachedGenreTracks } from './seedCache';

/**
 * Three daily-playlists per active user:
 *
 *   - "Знакомое"   — 70% favourite-artist tracks + 30% close-similar.
 *                    For when the user just wants comfort food.
 *   - "Открытия"   — 100% tracks the user has not played, taste-aligned.
 *                    Spotify's Discover Weekly equivalent.
 *   - "Под настроение" — moodish slice based on time-of-day patterns
 *                    in the user's history (heuristic mood pick).
 *
 * Generated by the nightly cron, but also lazily on-demand if today's
 * row is missing (e.g. user logged in for the first time today before
 * cron ran, or is brand new). Cold-start users get genre-seeded
 * variants until they have meaningful history.
 */

const VARIANTS = ['familiar', 'discover', 'mood'] as const;
type Variant = typeof VARIANTS[number];

interface VariantSpec {
  variant: Variant;
  name: string;
  description: string;
}

interface ColdStartSpec extends VariantSpec {
  /** Genre slugs (Tidal page slugs) that mood the playlist if the user
   *  has no taste profile yet. The first slug also seeds the cover. */
  fallbackGenres: string[];
}

const SPECS: Record<Variant, ColdStartSpec> = {
  familiar: {
    variant: 'familiar',
    name: 'Знакомое',
    description: 'Любимые артисты и близкие к ним новинки',
    fallbackGenres: ['genre_pop', 'genre_rap'],
  },
  discover: {
    variant: 'discover',
    name: 'Открытия',
    description: 'То, что ты ещё не слушал, но точно зайдёт',
    fallbackGenres: ['genre_indie', 'genre_electronic'],
  },
  mood: {
    variant: 'mood',
    name: 'Под настроение',
    description: 'Подобрано под твой обычный вайб',
    fallbackGenres: ['mood_chill', 'mood_focus'],
  },
};

const PLAYLIST_LENGTH = 50;

interface DailyPlaylistRow {
  id: string;
  variant: Variant;
  name: string;
  description: string;
  cover_url: string | null;
  tracks: string;
  generated_at: number;
  saved_to_playlist_id: string | null;
}

export interface DailyPlaylist {
  id: string;
  variant: Variant;
  name: string;
  description: string;
  coverUrl?: string;
  tracks: Track[];
  generatedAt: number;
  /** When the user has promoted this daily-playlist into their library,
   *  this points at the resulting playlists.id. The home page uses this
   *  to render a persistent «Сохранено» badge across reloads. */
  savedToPlaylistId?: string;
}

export class DailyPlaylistService {
  private rec: RecommendationService;
  private taste: TasteService;
  private tidal: TidalService;

  constructor(private env: Env) {
    this.rec = new RecommendationService(env);
    this.taste = new TasteService(env);
    this.tidal = new TidalService(env);
  }

  /**
   * Return today's three playlists for the user. If any are missing,
   * generate them inline so first-day users still see content. Cron
   * keeps things fresh for everyone else.
   */
  async getToday(userId: string): Promise<DailyPlaylist[]> {
    const today = isoDate(Date.now());
    const existing = await this.fetchByDate(userId, today);
    const got = new Set(existing.map((p) => p.variant));
    const missing = VARIANTS.filter((v) => !got.has(v));
    if (missing.length === 0) return existing;

    const generated = await this.generateVariants(userId, missing);
    return [...existing, ...generated].sort(byVariantOrder);
  }

  /**
   * Cron-friendly: regenerate today's playlists for one user. Replaces
   * any existing rows for the same date+variant.
   */
  async regenerate(userId: string): Promise<DailyPlaylist[]> {
    return this.generateVariants(userId, [...VARIANTS]);
  }

  /**
   * Garbage-collect playlists older than 7 days that the user never
   * promoted into their library.
   */
  async gc(): Promise<void> {
    const cutoff = isoDate(Date.now() - 7 * 24 * 60 * 60 * 1000);
    await this.env.DB
      .prepare(`DELETE FROM daily_playlists WHERE date < ?`)
      .bind(cutoff)
      .run();
  }

  // ---------- private ----------

  private async fetchByDate(userId: string, date: string): Promise<DailyPlaylist[]> {
    const res = await this.env.DB
      .prepare(
        `SELECT id, variant, name, description, cover_url, tracks,
                generated_at, saved_to_playlist_id
           FROM daily_playlists
          WHERE user_id = ? AND date = ?`,
      )
      .bind(userId, date)
      .all<DailyPlaylistRow>();
    return (res.results ?? []).map((r) => ({
      id: r.id,
      variant: r.variant,
      name: r.name,
      description: r.description,
      coverUrl: r.cover_url ?? undefined,
      tracks: parseTracks(r.tracks),
      generatedAt: r.generated_at,
      savedToPlaylistId: r.saved_to_playlist_id ?? undefined,
    })).sort(byVariantOrder);
  }

  private async generateVariants(userId: string, variants: Variant[]): Promise<DailyPlaylist[]> {
    const { profile, genreSeeds } = await this.taste.getOrCompute(userId);
    const today = isoDate(Date.now());
    const out: DailyPlaylist[] = [];

    // Belt-and-braces: the wave-driven variants already filter via
    // `RecommendationService.rerank`, but the genre-seeded mood variant
    // pulls straight from explore pages and otherwise wouldn't honour
    // the user's dislike list. Apply a final filter here so all three
    // variants stay consistent.
    const dislikes = await loadDislikes(this.env, userId);

    // Cross-variant claim-set. Familiar / discover / mood used to be
    // built independently and each call into `rec.wave()` without a
    // character returned the SAME taste-aligned pool, so playlists
    // 1 and 3 frequently shipped overlapping (or identical) tracks
    // — user reported "плейлисты 1 и 3 как будто содержат одни и те же
    // треки". The fix is two-pronged: (1) each variant calls
    // `rec.wave` with its OWN `character` so the underlying rerank
    // produces distinct results (familiar pushes known-favourite
    // bias, discover penalises it); (2) once a track has been picked
    // into one variant we mark it as claimed and skip it everywhere
    // else, including during backfill. The order — familiar →
    // discover → mood — means the most user-aligned variant gets
    // first dibs on the tightest pool and mood is left to differentiate
    // via genre/mood-tagged tracks the others wouldn't have surfaced.
    const claimed = new Set<string>();
    // Sort the input list into the canonical variant order so the
    // claim semantics stay deterministic regardless of which subset
    // the caller asked for (cron passes all three; lazy on-read can
    // pass a subset).
    const ordered = variants.slice().sort((a, b) => VARIANTS.indexOf(a) - VARIANTS.indexOf(b));

    for (const variant of ordered) {
      const spec = SPECS[variant];
      const built = await this.buildVariantTracks(
        variant,
        userId,
        profile.completedTrackIds,
        genreSeeds,
        claimed,
      );
      let tracks = filterTracksByDislikes(built, dislikes);
      // Anti-overlap: even after the variant-specific build the
      // upstream pools (track-radio, genre pages, wave) can echo into
      // each other for users with narrow taste. Strip anything a
      // previous variant already shipped.
      tracks = tracks.filter((t) => !claimed.has(trackKey(t)));

      // Backfill so each variant always reaches PLAYLIST_LENGTH when
      // possible. Without this the user would intermittently see
      // 10–30 tracks on a daily playlist whenever the wave/genre
      // pool came back short or after dislikes filtered out enough
      // candidates to drop the count under the cap. Cycle through
      // the variant's fallback genres + the user's taste-derived
      // genre seeds so we exhaust reasonable sources before
      // shipping a partial playlist.
      if (tracks.length < PLAYLIST_LENGTH) {
        const fallbackSlugs = [
          ...spec.fallbackGenres,
          ...genreSeeds,
          'genre_pop',
          'genre_rap',
          'genre_electronic',
        ];
        const seenSlugs = new Set<string>();
        for (const slug of fallbackSlugs) {
          if (tracks.length >= PLAYLIST_LENGTH) break;
          if (seenSlugs.has(slug)) continue;
          seenSlugs.add(slug);
          const filler = filterTracksByDislikes(
            await this.tracksFromGenre(slug),
            dislikes,
          ).filter((t) => !claimed.has(trackKey(t)));
          tracks = mergeUnique(tracks, filler, PLAYLIST_LENGTH);
        }
      }

      // Hard cap so a backfill that overshoots can't ship more than
      // the contracted PLAYLIST_LENGTH (the home-page UI assumes 50).
      if (tracks.length > PLAYLIST_LENGTH) tracks = tracks.slice(0, PLAYLIST_LENGTH);
      if (tracks.length === 0) continue;

      // Claim every track shipped in this variant so the next variant
      // in `ordered` can't ship the same id again. Has to run AFTER
      // the slice/cap so partial-playlist fallbacks don't pre-claim
      // tracks they ended up not using.
      for (const t of tracks) claimed.add(trackKey(t));

      const cover = pickCover(tracks);
      const name = spec.name;
      const description = spec.description;
      const id = crypto.randomUUID();
      const generatedAt = Date.now();

      await this.env.DB
        .prepare(
          `INSERT INTO daily_playlists
             (id, user_id, date, variant, name, description, cover_url, tracks, generated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(user_id, date, variant) DO UPDATE SET
             id = excluded.id,
             name = excluded.name,
             description = excluded.description,
             cover_url = excluded.cover_url,
             tracks = excluded.tracks,
             generated_at = excluded.generated_at`,
        )
        .bind(id, userId, today, variant, name, description, cover ?? null, JSON.stringify(tracks), generatedAt)
        .run();

      out.push({ id, variant, name, description, coverUrl: cover, tracks, generatedAt });
    }

    return out.sort(byVariantOrder);
  }

  private async buildVariantTracks(
    variant: Variant,
    userId: string,
    completedTrackIds: string[],
    genreSeeds: string[],
    claimed: Set<string>,
  ): Promise<Track[]> {
    const hasHistory = completedTrackIds.length > 0;

    if (variant === 'familiar') {
      // Familiar leans into stuff the user already knows / loves:
      // call wave with `character: 'familiar'` so the rerank doubles
      // W_FAMILIAR_BONUS instead of running the neutral profile. We
      // oversample (2× PLAYLIST_LENGTH) so the cross-variant claim
      // strip in `generateVariants` doesn't shrink the final result
      // below the contracted length.
      const wave = await this.rec.wave(userId, {
        limit: PLAYLIST_LENGTH * 2,
        character: 'familiar',
      });
      const familiarHead = wave.slice(0, Math.floor(PLAYLIST_LENGTH * 0.7));
      // Padding from completed tracks if wave came back short.
      const padPool = await this.tracksFromIds(completedTrackIds.slice(0, 30));
      return mergeUnique(familiarHead, padPool, PLAYLIST_LENGTH * 2);
    }

    if (variant === 'discover') {
      // Discover flips W_FAMILIAR_BONUS into a penalty inside the
      // rerank (`character: 'discover'`) so the pool comes back
      // taste-adjacent but tilted toward fresh artists — a genuinely
      // different distribution from familiar's pool, NOT just
      // "familiar minus history". Oversample 3× so the history-strip
      // + cross-variant-claim still leaves us PLAYLIST_LENGTH room.
      const wave = await this.rec.wave(userId, {
        limit: PLAYLIST_LENGTH * 3,
        character: 'discover',
      });
      // Strip anything in the user's history → real "discovery".
      const known = new Set(completedTrackIds);
      const unknown = wave.filter((t) => !known.has(t.id) && !claimed.has(trackKey(t)));
      if (unknown.length >= PLAYLIST_LENGTH) return unknown.slice(0, PLAYLIST_LENGTH);
      // Pad with a genre-seeded pool when wave came back short.
      // Previously this only ran for cold-start users (no history),
      // which meant returning users with a thin wave got a partial
      // (10–30 track) discover playlist instead of the contracted 50.
      const fillerSlug = genreSeeds[0] ?? SPECS.discover.fallbackGenres[0] ?? 'genre_pop';
      const filler = (await this.tracksFromGenre(fillerSlug))
        .filter((t) => !known.has(t.id) && !claimed.has(trackKey(t)));
      return mergeUnique(unknown, filler, PLAYLIST_LENGTH);
    }

    // mood — pick the slug from the user's actual time-of-day pattern
    // when we have enough history, fall back to wall-clock UTC hour
    // for cold-start users. The primary source is the mood-tagged
    // explore page (a fundamentally different pool from familiar /
    // discover); only fall back to wave when that pool is too thin
    // to reach PLAYLIST_LENGTH, in which case we also pass the same
    // mood signal into wave so the filler pool is still mood-tinted
    // instead of returning the neutral pool that used to overlap
    // with familiar.
    const moodSlug = await this.pickPersonalMoodSlug(userId, hasHistory);
    const moodTracks = (await this.tracksFromGenre(moodSlug))
      .filter((t) => !claimed.has(trackKey(t)));
    if (moodTracks.length >= PLAYLIST_LENGTH) return moodTracks.slice(0, PLAYLIST_LENGTH);
    // Map our internal mood slug back to the WaveMood enum used by
    // `rec.wave` so the filler pool gets a mood-pool boost in rerank.
    // Best-effort: if the slug doesn't map (e.g. a future mood without
    // a matching enum), call wave without the mood and accept the
    // neutral filler.
    const moodEnum = moodSlugToWaveMood(moodSlug);
    const fillerWave = await this.rec.wave(userId, {
      limit: PLAYLIST_LENGTH * 2,
      mood: moodEnum,
    });
    const fillerFiltered = fillerWave.filter((t) => !claimed.has(trackKey(t)));
    return mergeUnique(moodTracks, fillerFiltered, PLAYLIST_LENGTH);
  }

  private async tracksFromIds(ids: string[]): Promise<Track[]> {
    if (ids.length === 0) return [];
    // Cheap: fan out individual track fetches. Tidal has no bulk endpoint
    // we use elsewhere, and these requests get hit rarely enough that
    // serialised parallel fetch with a small cap is fine.
    const limited = ids.slice(0, 15);
    const results = await Promise.all(limited.map(async (id) => {
      try {
        const radio = await this.tidal.getTrackRadio(id);
        return radio[0] ?? null;
      } catch {
        return null;
      }
    }));
    return results.filter((t): t is Track => t !== null);
  }

  private async tracksFromGenre(slug: string): Promise<Track[]> {
    return getCachedGenreTracks(this.env, this.tidal, slug);
  }

  /**
   * Map the *current* hour to a mood slug, biased by the user's actual
   * listening pattern. We bucket their last 30 days of plays into four
   * 6-hour quadrants, work out which mood each quadrant the user most
   * resembles, and use *now's* quadrant.
   *
   * The previous implementation just used UTC wall-clock hour for
   * everyone, which made the "Под настроение" daily playlist feel
   * generic and out of sync with the user's actual habits. Cold-start
   * users (no history) still fall back to wall-clock since there's
   * nothing better to ask.
   */
  private async pickPersonalMoodSlug(userId: string, hasHistory: boolean): Promise<string> {
    const wallClock = pickMoodSlugByHour(new Date().getUTCHours());
    if (!hasHistory) return wallClock;

    const since = Date.now() - 30 * 24 * 60 * 60 * 1000;
    const rows = await this.env.DB
      .prepare(`SELECT played_at FROM play_history WHERE user_id = ? AND played_at >= ?`)
      .bind(userId, since)
      .all<{ played_at: number }>();

    // Count plays per quadrant (0-5h, 6-11h, 12-17h, 18-23h).
    const buckets = [0, 0, 0, 0];
    for (const r of rows.results ?? []) {
      const h = new Date(r.played_at).getUTCHours();
      buckets[Math.floor(h / 6)]! += 1;
    }
    const total = buckets.reduce((a, b) => a + b, 0);
    if (total < 20) return wallClock; // not enough signal yet

    // Each quadrant has a "default" mood. We pick the slug for the
    // quadrant that *now* falls into — but we also amplify the choice
    // when the user shows a strong concentration there (>40% of plays
    // in a single 6h window: stick to that quadrant's mood). A more
    // diffuse pattern → just use now's quadrant. This is intentionally
    // simple; full audio-features clustering is the next step up.
    const nowQuadrant = Math.floor(new Date().getUTCHours() / 6);
    const QUADRANT_MOOD: string[] = ['mood_chill', 'mood_focus', 'mood_workout', 'mood_chill'];
    const peakQuadrant = buckets.indexOf(Math.max(...buckets));
    const peakShare = total > 0 ? (buckets[peakQuadrant] ?? 0) / total : 0;
    const slug = peakShare > 0.4
      ? QUADRANT_MOOD[peakQuadrant]
      : QUADRANT_MOOD[nowQuadrant];
    return slug ?? wallClock;
  }
}

function isoDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

function byVariantOrder(a: { variant: Variant }, b: { variant: Variant }): number {
  return VARIANTS.indexOf(a.variant) - VARIANTS.indexOf(b.variant);
}

function pickCover(tracks: Track[]): string | undefined {
  for (const t of tracks) {
    if (t.coverUrl) return t.coverUrl;
  }
  return undefined;
}

function pickMoodSlugByHour(hour: number): string {
  // Wall-clock fallback used by cold-start users (no history yet).
  // Late evening → chill, morning → focus, mid-day → workout.
  if (hour < 8) return 'mood_chill';
  if (hour < 13) return 'mood_focus';
  if (hour < 19) return 'mood_workout';
  return 'mood_chill';
}

function parseTracks(raw: string): Track[] {
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (Array.isArray(parsed)) return parsed as Track[];
  } catch { /* ignore */ }
  return [];
}

function mergeUnique(a: Track[], b: Track[], cap: number): Track[] {
  const seen = new Set<string>();
  const out: Track[] = [];
  for (const t of [...a, ...b]) {
    const key = trackKey(t);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(t);
    if (out.length >= cap) break;
  }
  return out;
}

/**
 * Canonical cross-table key for a track: source-namespaced track id.
 * Used by both `mergeUnique` (for in-pool dedup) and the cross-variant
 * `claimed` set in `generateVariants` so a user/tidal/upload track
 * can't be ambiguously claimed by two providers under the same id.
 */
function trackKey(t: Track): string {
  return `${t.source ?? 'tidal'}:${t.id}`;
}

/**
 * Map an internal `mood_<slug>` (the format we store in
 * `daily_playlists.variant` rows and that
 * `pickPersonalMoodSlug` returns) to the `WaveMood` enum understood
 * by `RecommendationService.wave({ mood })`. Returns `null` when the
 * slug isn't a mood enum (e.g. a future quadrant default or a generic
 * genre slug) — callers can treat that as "no mood bias" and pass the
 * neutral wave through.
 */
function moodSlugToWaveMood(slug: string): WaveMood | null {
  // The WAVE_MOODS tuple is the source of truth for valid enum values;
  // slugs in this codebase are uniformly `mood_<enum>` so the prefix
  // strip + table lookup is exact (no fuzzy matching).
  const stripped = slug.replace(/^mood_/, '');
  for (const m of WAVE_MOODS) {
    if (m === stripped) return m;
  }
  return null;
}
