import type { Env } from '../types/env';
import type { Track } from '../types/music';
import { RecommendationService } from './RecommendationService';
import { TasteService } from './TasteService';
import { TidalService } from './tidal/TidalService';
import { loadDislikes, filterTracksByDislikes } from './dislikes';

/**
 * Three daily-playlists per active user:
 *
 *   - "Знакомое"   — 70% favourite-artist tracks + 30% close-similar.
 *                    For when the user just wants comfort food.
 *   - "Открытия"   — 100% tracks the user has not played, taste-aligned.
 *                    Spotify's Discover Weekly equivalent.
 *   - "Под настроение" — moodish slice based on time-of-day patterns
 *                    in the user's history (heuristic mood pick).
 *
 * Generated by the nightly cron, but also lazily on-demand if today's
 * row is missing (e.g. user logged in for the first time today before
 * cron ran, or is brand new). Cold-start users get genre-seeded
 * variants until they have meaningful history.
 */

const VARIANTS = ['familiar', 'discover', 'mood'] as const;
type Variant = typeof VARIANTS[number];

interface VariantSpec {
  variant: Variant;
  name: string;
  description: string;
}

interface ColdStartSpec extends VariantSpec {
  /** Genre slugs (Tidal page slugs) that mood the playlist if the user
   *  has no taste profile yet. The first slug also seeds the cover. */
  fallbackGenres: string[];
}

const SPECS: Record<Variant, ColdStartSpec> = {
  familiar: {
    variant: 'familiar',
    name: 'Знакомое',
    description: 'Любимые артисты и близкие к ним новинки',
    fallbackGenres: ['genre_pop', 'genre_rap'],
  },
  discover: {
    variant: 'discover',
    name: 'Открытия',
    description: 'То, что ты ещё не слушал, но точно зайдёт',
    fallbackGenres: ['genre_indie', 'genre_electronic'],
  },
  mood: {
    variant: 'mood',
    name: 'Под настроение',
    description: 'Подобрано под твой обычный вайб',
    fallbackGenres: ['mood_chill', 'mood_focus'],
  },
};

const PLAYLIST_LENGTH = 50;

interface DailyPlaylistRow {
  id: string;
  variant: Variant;
  name: string;
  description: string;
  cover_url: string | null;
  tracks: string;
  generated_at: number;
  saved_to_playlist_id: string | null;
}

export interface DailyPlaylist {
  id: string;
  variant: Variant;
  name: string;
  description: string;
  coverUrl?: string;
  tracks: Track[];
  generatedAt: number;
  /** When the user has promoted this daily-playlist into their library,
   *  this points at the resulting playlists.id. The home page uses this
   *  to render a persistent «Сохранено» badge across reloads. */
  savedToPlaylistId?: string;
}

export class DailyPlaylistService {
  private rec: RecommendationService;
  private taste: TasteService;
  private tidal: TidalService;

  constructor(private env: Env) {
    this.rec = new RecommendationService(env);
    this.taste = new TasteService(env);
    this.tidal = new TidalService(env);
  }

  /**
   * Return today's three playlists for the user. If any are missing,
   * generate them inline so first-day users still see content. Cron
   * keeps things fresh for everyone else.
   */
  async getToday(userId: string): Promise<DailyPlaylist[]> {
    const today = isoDate(Date.now());
    const existing = await this.fetchByDate(userId, today);
    const got = new Set(existing.map((p) => p.variant));
    const missing = VARIANTS.filter((v) => !got.has(v));
    if (missing.length === 0) return existing;

    const generated = await this.generateVariants(userId, missing);
    return [...existing, ...generated].sort(byVariantOrder);
  }

  /**
   * Cron-friendly: regenerate today's playlists for one user. Replaces
   * any existing rows for the same date+variant.
   */
  async regenerate(userId: string): Promise<DailyPlaylist[]> {
    return this.generateVariants(userId, [...VARIANTS]);
  }

  /**
   * Garbage-collect playlists older than 7 days that the user never
   * promoted into their library.
   */
  async gc(): Promise<void> {
    const cutoff = isoDate(Date.now() - 7 * 24 * 60 * 60 * 1000);
    await this.env.DB
      .prepare(`DELETE FROM daily_playlists WHERE date < ?`)
      .bind(cutoff)
      .run();
  }

  // ---------- private ----------

  private async fetchByDate(userId: string, date: string): Promise<DailyPlaylist[]> {
    const res = await this.env.DB
      .prepare(
        `SELECT id, variant, name, description, cover_url, tracks,
                generated_at, saved_to_playlist_id
           FROM daily_playlists
          WHERE user_id = ? AND date = ?`,
      )
      .bind(userId, date)
      .all<DailyPlaylistRow>();
    return (res.results ?? []).map((r) => ({
      id: r.id,
      variant: r.variant,
      name: r.name,
      description: r.description,
      coverUrl: r.cover_url ?? undefined,
      tracks: parseTracks(r.tracks),
      generatedAt: r.generated_at,
      savedToPlaylistId: r.saved_to_playlist_id ?? undefined,
    })).sort(byVariantOrder);
  }

  private async generateVariants(userId: string, variants: Variant[]): Promise<DailyPlaylist[]> {
    const { profile, genreSeeds } = await this.taste.getOrCompute(userId);
    const today = isoDate(Date.now());
    const out: DailyPlaylist[] = [];

    // Belt-and-braces: the wave-driven variants already filter via
    // `RecommendationService.rerank`, but the genre-seeded mood variant
    // pulls straight from explore pages and otherwise wouldn't honour
    // the user's dislike list. Apply a final filter here so all three
    // variants stay consistent.
    const dislikes = await loadDislikes(this.env, userId);

    for (const variant of variants) {
      const spec = SPECS[variant];
      const built = await this.buildVariantTracks(variant, userId, profile.completedTrackIds, genreSeeds);
      const tracks = filterTracksByDislikes(built, dislikes);
      if (tracks.length === 0) continue;

      const cover = pickCover(tracks);
      const name = spec.name;
      const description = spec.description;
      const id = crypto.randomUUID();
      const generatedAt = Date.now();

      await this.env.DB
        .prepare(
          `INSERT INTO daily_playlists
             (id, user_id, date, variant, name, description, cover_url, tracks, generated_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(user_id, date, variant) DO UPDATE SET
             id = excluded.id,
             name = excluded.name,
             description = excluded.description,
             cover_url = excluded.cover_url,
             tracks = excluded.tracks,
             generated_at = excluded.generated_at`,
        )
        .bind(id, userId, today, variant, name, description, cover ?? null, JSON.stringify(tracks), generatedAt)
        .run();

      out.push({ id, variant, name, description, coverUrl: cover, tracks, generatedAt });
    }

    return out.sort(byVariantOrder);
  }

  private async buildVariantTracks(
    variant: Variant,
    userId: string,
    completedTrackIds: string[],
    genreSeeds: string[],
  ): Promise<Track[]> {
    const hasHistory = completedTrackIds.length > 0;

    if (variant === 'familiar') {
      // 70% from wave (which respects taste); 30% known favourites.
      // We re-use wave so the rerank stays in one place.
      const wave = await this.rec.wave(userId, PLAYLIST_LENGTH);
      const familiar = wave.slice(0, Math.floor(PLAYLIST_LENGTH * 0.7));
      // Padding from completed tracks if wave came back short.
      const padPool = await this.tracksFromIds(completedTrackIds.slice(0, 30));
      return mergeUnique(familiar, padPool, PLAYLIST_LENGTH);
    }

    if (variant === 'discover') {
      const wave = await this.rec.wave(userId, PLAYLIST_LENGTH * 2);
      // Strip anything in the user's history → real "discovery".
      const known = new Set(completedTrackIds);
      const unknown = wave.filter((t) => !known.has(t.id));
      if (unknown.length >= PLAYLIST_LENGTH) return unknown.slice(0, PLAYLIST_LENGTH);
      // Cold-start fallback: fetch genre tracks for the first picked genre.
      const filler = hasHistory ? [] : await this.tracksFromGenre(genreSeeds[0] ?? 'genre_pop');
      return mergeUnique(unknown, filler, PLAYLIST_LENGTH);
    }

    // mood
    const moodSlug = pickMoodSlug();
    const moodTracks = await this.tracksFromGenre(moodSlug);
    if (moodTracks.length >= PLAYLIST_LENGTH) return moodTracks.slice(0, PLAYLIST_LENGTH);
    const fillerWave = await this.rec.wave(userId, PLAYLIST_LENGTH);
    return mergeUnique(moodTracks, fillerWave, PLAYLIST_LENGTH);
  }

  private async tracksFromIds(ids: string[]): Promise<Track[]> {
    if (ids.length === 0) return [];
    // Cheap: fan out individual track fetches. Tidal has no bulk endpoint
    // we use elsewhere, and these requests get hit rarely enough that
    // serialised parallel fetch with a small cap is fine.
    const limited = ids.slice(0, 15);
    const results = await Promise.all(limited.map(async (id) => {
      try {
        const radio = await this.tidal.getTrackRadio(id);
        return radio[0] ?? null;
      } catch {
        return null;
      }
    }));
    return results.filter((t): t is Track => t !== null);
  }

  private async tracksFromGenre(slug: string): Promise<Track[]> {
    try {
      const cached = await this.env.SESSIONS.get(`genre_seed_tracks:${slug}`, 'json');
      if (cached && Array.isArray(cached)) return cached as Track[];
      const page = await this.tidal.getExplorePage(slug);
      const tracks: Track[] = [];
      for (const m of page.modules) {
        if (m.type === 'tracks') tracks.push(...m.items);
      }
      await this.env.SESSIONS.put(`genre_seed_tracks:${slug}`, JSON.stringify(tracks.slice(0, 60)), {
        expirationTtl: 12 * 60 * 60,
      });
      return tracks;
    } catch {
      return [];
    }
  }
}

function isoDate(ts: number): string {
  return new Date(ts).toISOString().slice(0, 10);
}

function byVariantOrder(a: { variant: Variant }, b: { variant: Variant }): number {
  return VARIANTS.indexOf(a.variant) - VARIANTS.indexOf(b.variant);
}

function pickCover(tracks: Track[]): string | undefined {
  for (const t of tracks) {
    if (t.coverUrl) return t.coverUrl;
  }
  return undefined;
}

function pickMoodSlug(): string {
  const hour = new Date().getUTCHours();
  // Lightweight heuristic: late evening → chill, morning → focus,
  // mid-day → upbeat. The cron runs once a day so this picks the slug
  // for the time the cron fires (or the time the user first hits
  // /today on day 1 — close enough). A fancier version would be
  // per-user time-of-day sampling from history.
  if (hour < 8) return 'mood_chill';
  if (hour < 13) return 'mood_focus';
  if (hour < 19) return 'mood_workout';
  return 'mood_chill';
}

function parseTracks(raw: string): Track[] {
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (Array.isArray(parsed)) return parsed as Track[];
  } catch { /* ignore */ }
  return [];
}

function mergeUnique(a: Track[], b: Track[], cap: number): Track[] {
  const seen = new Set<string>();
  const out: Track[] = [];
  for (const t of [...a, ...b]) {
    const key = `${t.source ?? 'tidal'}:${t.id}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(t);
    if (out.length >= cap) break;
  }
  return out;
}
