-- Listening history, taste profile, dislikes, daily-playlists, anti-repeat
-- cache. Together these power the "Моя волна", endless playback and
-- "Плейлист дня" features without leaking per-user signal back into the
-- shared Tidal proxy account: each user's profile lives entirely in our D1,
-- and the Tidal API is only ever queried with content-seeded primitives
-- (tracks/{id}/radio, artists/{id}/similar) that are not personalised on
-- the upstream side.

-- One row per significant play. We log when the audio engine has
-- played a track for >= 30s OR the track ended naturally. Skipping
-- earlier than 30s does NOT create a row (we don't want to pollute
-- the taste vector with what the user actively rejected). A short
-- track that played to completion still counts — completed-pct
-- handles that.
CREATE TABLE play_history (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    track_id         TEXT NOT NULL,
    source           TEXT NOT NULL DEFAULT 'tidal',
    artist_id        TEXT,
    artist_name      TEXT NOT NULL DEFAULT '',
    title            TEXT NOT NULL DEFAULT '',
    album_id         TEXT,
    cover_url        TEXT,
    duration         INTEGER NOT NULL DEFAULT 0,
    listened_seconds INTEGER NOT NULL DEFAULT 0,
    -- 1 if the user heard >= 80% of the track (or it ended naturally).
    -- Used as the strongest positive signal in taste-profile recompute.
    completed        INTEGER NOT NULL DEFAULT 0,
    played_at        INTEGER NOT NULL
);
CREATE INDEX idx_play_history_user_played ON play_history(user_id, played_at DESC);
CREATE INDEX idx_play_history_user_artist ON play_history(user_id, artist_id);

-- Serialised per-user taste vector. Recomputed nightly by the cron
-- trigger, and on-demand by the recommendation service when the
-- existing snapshot is older than 24h or doesn't exist yet.
--
-- The blob is JSON of the form:
--   {
--     "artistWeights": { "<artist_id>": <0..1 normalised score>, ... },
--     "completedTrackIds": ["<id1>", "<id2>", ...],   // ≤ 50 most-completed
--     "totalPlays": 137,
--     "version": 1
--   }
-- We store as a single TEXT column (rather than a normalised
-- artist_weights table) because (a) the vector is fully replaced on
-- every recompute, (b) we always read it whole, never query individual
-- weights from SQL, and (c) it keeps cross-table joins out of the hot
-- recommendation path.
CREATE TABLE user_taste_profile (
    user_id      TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    profile      TEXT NOT NULL,
    -- Genres the user picked during cold-start onboarding. JSON array of
    -- Tidal page slugs ("genre_rap", "genre_jazz", ...). Used as the
    -- candidate-pool seed before the user has any real listening history.
    genre_seeds  TEXT NOT NULL DEFAULT '[]',
    computed_at  INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL
);

-- Explicit dislikes. Tracks/artists hit with a "не нравится" button get a
-- hard negative weight in re-rank (and excluded entirely from candidate
-- generation for a while).
CREATE TABLE user_dislikes (
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    item_id    TEXT NOT NULL,
    kind       TEXT NOT NULL CHECK(kind IN ('track','artist')),
    source     TEXT NOT NULL DEFAULT 'tidal',
    created_at INTEGER NOT NULL,
    PRIMARY KEY (user_id, item_id, kind)
);
CREATE INDEX idx_user_dislikes_user ON user_dislikes(user_id, created_at DESC);

-- Three daily-playlists per active user, generated by the nightly cron
-- (or on-demand if today's row is missing). The user can promote a
-- variant to a permanent playlist via the "Сохранить в библиотеку"
-- button — that copies the rows into `playlists` + `playlist_tracks` and
-- leaves this row untouched. After 7 days unsaved rows are GC'd.
CREATE TABLE daily_playlists (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    date         TEXT NOT NULL,
    variant      TEXT NOT NULL CHECK(variant IN ('familiar','discover','mood')),
    name         TEXT NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    cover_url    TEXT,
    tracks       TEXT NOT NULL,
    generated_at INTEGER NOT NULL
);
CREATE UNIQUE INDEX idx_daily_playlists_user_date_variant ON daily_playlists(user_id, date, variant);
CREATE INDEX idx_daily_playlists_user_generated ON daily_playlists(user_id, generated_at DESC);

-- Anti-repeat cache: the tracks we've shown to this user in the last
-- 7 days. Used to penalise candidates in the re-rank step so the wave
-- doesn't loop the same 20 songs forever. GC'd by the cron after 14d.
CREATE TABLE recommendation_seen (
    user_id      TEXT NOT NULL,
    track_id     TEXT NOT NULL,
    source       TEXT NOT NULL DEFAULT 'tidal',
    last_seen_at INTEGER NOT NULL,
    PRIMARY KEY (user_id, track_id, source)
);
CREATE INDEX idx_recommendation_seen_user_seen ON recommendation_seen(user_id, last_seen_at DESC);
